zuul:
  ignored-services: "*"
  routes:
    hydra_realm1:
      path: /hydra/realm1/**
      url: http://localhost:4444
      # Spring Boot strips some sensitive headers by default (Authorization is one of them)
      # Disable the blacklist
      sensitiveHeaders:
    balances:
      path: /balances/**
      url: http://localhost:10000/balances
    accounts:
      path: /accounts/**
      url: http://localhost:10000/accounts
ribbon:
  eureka:
    enabled: false
server:
  port: 8080