zuul:
  ignored-services: "*"
ribbon:
  eureka:
    enabled: false

# Env var is SERVER_PORT
server:
  port: 8080

# Env var is ADMIN_PORT
admin:
  port: 9090
  context-path: /

management:
  port: 8081
  context-path: /monitoring

store:
  cassandra:
    enabled: true
    routing: true
    plugins: true
    consumers: true

# Cassandra configuration
# Can also be passed as environment variables:
#   CASSANDRA_CONTACT_POINTS[0]=127.0.0.1
#   CASSANDRA_CONTACT_POINTS[1]=localhost
#   CASSANDRA_PORT=9042
cassandra:
  contact-points:
    - localhost
  port: 9042
  initial-connection-retry-count: 25
  wait-time-before-retries-in-sec: 4


# Pass your own environment variables
#   OAUTH2_CLIENT_ID=991635e3-c17a-4960-90f1-9908d4a8b333
#   OAUTH2_CLIENT_SECRET=ihLMuaB59cGkAqqD,pxKd&4LBL
oauth2:
  client_id: 991635e3-c17a-4960-90f1-9908d4a8b333
  client_secret: ihLMuaB59cGkAqqD,pxKd&4LBL

spring:
  application:
    name: Acheron
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest